export const NEWS_LOADED = 'NEWS_LOADED';
export const SET_CURRENT_NEWS_ITEM = 'SET_CURRENT_NEWS_ITEM';
export const INCREMENT_PAGE_COUNT = 'INCREMENT_PAGE_COUNT';
export const NO_NEWS_TO_FETCH = 'NO_NEWS_TO_FETCH';
